CREATE DATABASE IF NOT EXISTS anoweb;
USE anoweb;
CREATE TABLE IF NOT EXISTS profile_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    email VARCHAR(100),
    github VARCHAR(100),
    linkedin VARCHAR(100),
    bio VARCHAR(200)
);
CREATE TABLE IF NOT EXISTS experiences (
    id INT PRIMARY KEY AUTO_INCREMENT,
    company VARCHAR(100),
    position VARCHAR(100),
    start_date DATE,
    end_date DATE,
    present BOOLEAN,
    description TEXT,
    image_url VARCHAR(200),
    order_index INT
);
CREATE TABLE IF NOT EXISTS educations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    school VARCHAR(100),
    degree VARCHAR(100),
    start_date DATE,
    end_date DATE,
    link VARCHAR(200),
    image_url VARCHAR(200)
);
CREATE TABLE IF NOT EXISTS projects (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    description TEXT,
    link VARCHAR(200),
    image_url VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS studys (
    id INT PRIMARY KEY AUTO_INCREMENT,
    topic VARCHAR(100), 
    description TEXT,
    image_url VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    parent_id INT NOT NULL,
    parent_type VARCHAR(50) NOT NULL,
    name VARCHAR(100),
    content_md TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);